services:
  - type: web
    name: greysoft-website
    env: static
    staticPublishPath: ./dist/spa
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 16
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /index.html
        name: Cache-Control
        value: no-cache
